name: date
description: Implementacion de fecha que solo tiene en cuenta el dia, el mes y el año.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.0

# Add regular dependencies here.
dependencies:
  intl: ^0.18.1
  dartx: ^1.2.0

dev_dependencies:
  lints: ^2.1.1
  test: 1.24.6
